// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AccountInfo aggregates everything learnable about an account from its
 * refresh token and public Steam endpoints (no proxy, no API key).
 */
export interface AccountInfo {
    "steamId": string;
    "personaName": string;
    "realName"?: string;
    "avatarFull": string;
    "profileUrl": string;
    "visibility": string;
    "onlineState": string;
    "inGame"?: string;
    "location"?: string;
    "summary"?: string;
    "friendsCount": number;
    "topGame"?: string;
    "topGameHours"?: string;
    "level"?: string;
    "gamesCount"?: string;
    "banInfo"?: string;
    "banDays"?: string;
    "cs2Items": number;
    "cs2Rarity"?: string;
    "cs2Medals"?: string;
    "cs2Hours"?: string;
    "cs2Prime"?: string;
    "inventoryValue"?: string;
    "inventoryPartial"?: boolean;
    "licensesCount": number;
    "email"?: string;
    "wallet"?: string;
    "country"?: string;
    "vacBanned": boolean;
    "tradeBan": string;
    "limited": boolean;
    "memberSince": string;
    "tokenAlive": boolean;
    "profileErr"?: string;
    "tokenIssued"?: string;
    "tokenExpires"?: string;
    "tokenDaysLeft": number;
    "tokenAudiences"?: string;
    "tokenSteamId"?: string;
    "tokenClaimsJson"?: string;
    "tokenChecks": TokenCheck[] | null;
}

/**
 * BulkCheckItem is the per-account verdict of a bulk token check.
 * Status: "ok" (Steam CM accepted the token — login will work), "rejected",
 * "expired", "invalid", "error" (the check itself failed: network, rate limit).
 */
export interface BulkCheckItem {
    "account": string;
    "steamId"?: string;
    "status": string;
    "expiresAt"?: string;
    "detail"?: string;
}

/**
 * TokenCheck is one named verification of the refresh token.
 * Status is "ok", "fail" or "skip" (could not be evaluated).
 */
export interface TokenCheck {
    "id": string;
    "status": string;
}
