// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService is the Wails v3 backend service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "./internal/update/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdates queries GitHub Releases for a newer version.
 */
export function CheckForUpdates(): $CancellablePromise<update$0.Info> {
    return $Call.ByID(3671876993);
}

export function DeleteAccount(account: string): $CancellablePromise<$models.Result> {
    return $Call.ByID(991878028, account);
}

/**
 * GetAppName returns the product display name.
 */
export function GetAppName(): $CancellablePromise<string> {
    return $Call.ByID(1997395214);
}

export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(2729898890);
}

/**
 * InstallUpdate downloads the release exe and restarts into it.
 */
export function InstallUpdate(downloadURL: string): $CancellablePromise<$models.Result> {
    return $Call.ByID(3729456840, downloadURL);
}

export function ListAccounts(): $CancellablePromise<$models.AccountDTO[] | null> {
    return $Call.ByID(1560646494);
}

export function LoginFromKey(accountKey: string, keepExisting: boolean): $CancellablePromise<$models.Result> {
    return $Call.ByID(1019931498, accountKey, keepExisting);
}

export function LoginSaved(account: string, keepExisting: boolean): $CancellablePromise<$models.Result> {
    return $Call.ByID(2905720970, account, keepExisting);
}

/**
 * Notify shows a native Windows message box. Frontend should pass already-translated title/message.
 */
export function Notify(success: boolean, title: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(3513873047, success, title, message);
}

/**
 * OpenURL opens a link in the default browser.
 */
export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(790318107, url);
}

export function ResetSteam(): $CancellablePromise<$models.Result> {
    return $Call.ByID(2909845851);
}

export function WindowClose(): $CancellablePromise<void> {
    return $Call.ByID(233884162);
}

export function WindowMinimise(): $CancellablePromise<void> {
    return $Call.ByID(1381835851);
}
