// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService is the Wails v3 backend service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DeleteAccount(account: string): $CancellablePromise<$models.Result> {
    return $Call.ByID(991878028, account);
}

export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(2729898890);
}

export function ListAccounts(): $CancellablePromise<$models.AccountDTO[] | null> {
    return $Call.ByID(1560646494);
}

export function LoginFromKey(accountKey: string, keepExisting: boolean): $CancellablePromise<$models.Result> {
    return $Call.ByID(1019931498, accountKey, keepExisting);
}

export function LoginSaved(account: string, keepExisting: boolean): $CancellablePromise<$models.Result> {
    return $Call.ByID(2905720970, account, keepExisting);
}

export function ResetSteam(): $CancellablePromise<$models.Result> {
    return $Call.ByID(2909845851);
}

export function WindowClose(): $CancellablePromise<void> {
    return $Call.ByID(233884162);
}

export function WindowMinimise(): $CancellablePromise<void> {
    return $Call.ByID(1381835851);
}
