// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as steam$0 from "./internal/steam/models.js";

/**
 * AccountDTO is exposed to the frontend.
 */
export interface AccountDTO {
    "name": string;
    "expiresIn": string;
    "valid": boolean;
    "avatar"?: string;
}

/**
 * BulkCheckResult is the outcome of a bulk token check.
 */
export interface BulkCheckResult {
    "total": number;
    "items": steam$0.BulkCheckItem[] | null;
}

/**
 * Result is a generic UI response.
 */
export interface Result {
    "ok": boolean;
    "message": string;
}

/**
 * SystemStatus is the diagnostics snapshot for the Logs tab.
 */
export interface SystemStatus {
    "version": string;
    "steamRunning": boolean;
    "steamPath": string;
    "accountsTotal": number;
    "accountsValid": number;
    "driveConnected": boolean;
    "steamApiOnline": boolean;
}
