// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AccountDTO is exposed to the frontend.
 */
export interface AccountDTO {
    "name": string;
    "expiresIn": string;
    "valid": boolean;
}

/**
 * Result is a generic UI response.
 */
export interface Result {
    "ok": boolean;
    "message": string;
}
