// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Info is returned to the UI.
 */
export interface Info {
    "updateAvailable": boolean;
    "currentVersion": string;
    "latestVersion": string;
    "releaseUrl": string;
    "downloadUrl": string;
    "releaseNotes": string;
    "error"?: string;
}
