// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function LoginFromKey(arg1, arg2) {
  return window['go']['main']['App']['LoginFromKey'](arg1, arg2);
}

export function LoginSaved(arg1, arg2) {
  return window['go']['main']['App']['LoginSaved'](arg1, arg2);
}

export function ResetSteam() {
  return window['go']['main']['App']['ResetSteam']();
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}
