// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteAccount(arg1:string):Promise<main.Result>;

export function GetVersion():Promise<string>;

export function ListAccounts():Promise<Array<main.AccountDTO>>;

export function LoginFromKey(arg1:string,arg2:boolean):Promise<main.Result>;

export function LoginSaved(arg1:string,arg2:boolean):Promise<main.Result>;

export function ResetSteam():Promise<main.Result>;

export function WindowClose():Promise<void>;

export function WindowMinimise():Promise<void>;
