// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Status is exposed to the UI.
 */
export interface Status {
    "hasCredentials": boolean;
    "connected": boolean;
    "clientIdHint": string;
}
